First name instead of 'Profile' in right corner of header
cybernetisk/internsystem-v2 pull request #44
Opened 2024-09-23 07:00 UTC by yrjarv

Solves #42 
I have handled long names by making names longer than 25 characters be the first 22 chars plus "...".
One issue I can see is that "Stein Ole Knutsen" becomes just "Stein", even if the user prefers to be called "Stein Ole". However, I think this is the easiest solution in order to minimize the amount of times we have to shorten the name.
The width of the Grid containing LoginButton now automatically scales, and I have checked that it will automatically use the mobile version (where the text is below the icon, so text length doesn't cause a lot of issues) whenever making the window so small that there is almost a collision between the logo and the menu items.

2024-09-23 22:23 UTC, EricSvebakk requested changes
It looks like the mobile layout supports longer names well, but weird input will cause issues with the layout. Perhaps 25 characters is too much.

<img src="https://github.com/user-attachments/assets/5d849c79-12c4-4449-b815-30d76b91189b" width=200/>
<img src="https://github.com/user-attachments/assets/c9b3cf39-07af-4d75-ae4b-29b40022d0c0" width=200/>

It might be useful to look into refreshing the profile-page after a user has updated their name. I think NextJS has a method for their [useRouter()](https://nextjs.org/docs/app/api-reference/functions/use-router) hook that can forcefully refresh the server-side requests. Look into using useRouter.refresh()

2024-09-24 10:55 UTC, yrjarv commented
I have now reduced the max first name length, which now leads to no more issues when the viewport is small (eg on mobile). I however discovered another issue with AppBar, referenced in a separate issue (#47).
The only part of this solution that I am not happy with is 216dbd2, which is kinda hacky and doesn't quite implement @EricSvebakk 's suggestion as seen in the previous comment.

2024-09-24 11:13 UTC, EricSvebakk commented
The suggested fix looks promising. Reloading seems to work well, and the Login button seems to handle most strings.

However, I did find a potential issue. Names containing a hyphen may render incorrectly. This only seems to happen if you also have a string that is also too long. If you're able to fix this, then I believe the pull-request can be merged. If the issue persists, we could still decide to merge (and instead make it a new issue)

<img src="https://github.com/user-attachments/assets/71e7117b-7975-4ee6-a993-01d280dce8ad" width=200/>

2024-09-26 12:36 UTC, EricSvebakk approved these changes

2024-09-26 12:40 UTC, merged